import {
  DashboardAccountsAssetsLocation,
  DashboardAccountsChartsLocation,
  DashboardAccountsEventsLocation,
  DashboardAccountsFunctionsLocation,
  DashboardAccountsGasLocation,
  DashboardAccountsHistoryCustomLocation,
  DashboardAccountsHistoryEventsLocation,
  DashboardAccountsHistoryFunctionsLocation,
  DashboardAccountsHistoryLocation,
  DashboardAccountsHistoryReconsLocation,
  DashboardAccountsLocation,
  DashboardAccountsNeighborsLocation,
  DashboardCollectionsLocation,
  DashboardLocation,
  DashboardMonitorsLocation,
  ExplorerBlocksLocation,
  ExplorerLocation,
  ExplorerLogsLocation,
  ExplorerReceiptsLocation,
  ExplorerTracesLocation,
  ExplorerTransactionsLocation,
  NamesAddressesLocation,
  NamesBlocksLocation,
  NamesLocation,
  NamesSignaturesEventsLocation,
  NamesSignaturesFunctionsLocation,
  NamesSignaturesLocation,
  NamesTagsLocation,
  RootLocation,
  SettingsCachesLocation,
  SettingsDataModelLocation,
  SettingsIndexesChartsLocation,
  SettingsIndexesGridLocation,
  SettingsIndexesLocation,
  SettingsIndexesManifestLocation,
  SettingsIndexesTableLocation,
  SettingsLocation,
  SettingsScrapersLocation,
  SettingsSkinsLocation,
  SupportAboutUsLocation,
  SupportContactUsLocation,
  SupportDocumentationLocation,
  SupportHotKeysLocation,
  SupportLicensingLocation,
  SupportLocation,
} from './Routes';

export const helpRoutes = [
  {
    path: RootLocation,
    exact: true,
    render: () => 'The dashboard overview page gives you an overview of your holdings among other things.',
  },
  {
    path: DashboardLocation,
    exact: true,
    render: () => 'The dashboard overview page gives you an overview of your holdings among other things.',
  },
  {
    path: DashboardMonitorsLocation,
    exact: true,
    render: () => 'Monitors are named addresses that you have indicated are of interest and should be monitored by the scrapers.',
  },
  {
    path: DashboardAccountsLocation,
    exact: true,
    render: () => 'View the transactional history of an account.',
  },
  {
    path: DashboardAccountsAssetsLocation,
    exact: true,
    render: () => 'See all assets for a given address.',
  },
  {
    path: DashboardAccountsHistoryLocation,
    exact: true,
    render: () => 'View the transactional history of an account.',
  },
  {
    path: DashboardAccountsHistoryReconsLocation,
    exact: true,
    render: () => 'View the reconciliation history of an account.',
  },
  {
    path: DashboardAccountsHistoryFunctionsLocation,
    exact: true,
    render: () => 'View the functions for a transaction.',
  },
  {
    path: DashboardAccountsHistoryEventsLocation,
    exact: true,
    render: () => 'View the events in transaction.',
  },
  {
    path: DashboardAccountsHistoryCustomLocation,
    exact: true,
    render: () => 'View the logo of the to address for the transaction.',
  },
  {
    path: DashboardAccountsNeighborsLocation,
    exact: true,
    render: () => 'See all assets for a given address.',
  },
  {
    path: DashboardAccountsGasLocation,
    exact: true,
    render: () => 'Analyze gas usage.',
  },
  {
    path: DashboardAccountsChartsLocation,
    exact: true,
    render: () => 'See all assets for a given address.',
  },
  {
    path: DashboardAccountsFunctionsLocation,
    exact: true,
    render: () => 'See all assets for a given address.',
  },
  {
    path: DashboardAccountsEventsLocation,
    exact: true,
    render: () => 'See all assets for a given address.',
  },
  {
    path: DashboardCollectionsLocation,
    exact: true,
    render: () => 'Collections allow you to group together multiple monitored addresses.',
  },
  {
    path: NamesLocation,
    exact: true,
    render: () => 'Names are common or known addresses that have been given a name.',
  },
  {
    path: NamesAddressesLocation,
    exact: true,
    render: () => 'Named addresses are a convenient way to keep track of human-readable names for addresses.',
  },
  {
    path: NamesTagsLocation,
    exact: true,
    render: () => 'Tags are groupings used to collect together named addresses.',
  },
  {
    path: NamesSignaturesFunctionsLocation,
    exact: true,
    render: () => 'The function and event signatures tab allows you to add/edit/delete four byte signatures.',
  },
  {
    path: NamesSignaturesEventsLocation,
    exact: true,
    render: () => 'The function and event signatures tab allows you to add/edit/delete four byte signatures.',
  },
  {
    path: NamesSignaturesLocation,
    exact: true,
    render: () => 'The function and event signatures tab allows you to add/edit/delete four byte signatures.',
  },
  {
    path: NamesBlocksLocation,
    exact: true,
    render: () => 'The blocks tab allows you to name particular blocks such as smart contract deployments or hard forks.',
  },

  {
    path: ExplorerLocation,
    exact: true,
    render: () => 'View the contents of the TrueBlocks index cache.',
  },
  {
    path: ExplorerBlocksLocation,
    exact: true,
    render: () => 'View blockchain block details.',
  },
  {
    path: ExplorerTransactionsLocation,
    exact: true,
    render: () => 'View blockchain transaction details.',
  },
  {
    path: ExplorerReceiptsLocation,
    exact: true,
    render: () => 'View blockchain receipt details.',
  },
  {
    path: ExplorerLogsLocation,
    exact: true,
    render: () => 'View blockchain log details.',
  },
  {
    path: ExplorerTracesLocation,
    exact: true,
    render: () => 'View blockchain trace details.',
  },

  {
    path: SettingsLocation,
    exact: true,
    render: () => 'This screen allows you to adjust the way TrueBlocks two scrapers work.',
  },
  {
    path: SettingsScrapersLocation,
    exact: true,
    render: () => 'This screen allows you to adjust the way TrueBlocks two scrapers work.',
  },
  {
    path: SettingsIndexesLocation,
    exact: true,
    render: () => 'View the contents of the TrueBlocks index cache.',
  },
  {
    path: SettingsIndexesGridLocation,
    exact: true,
    render: () => 'Grid view of the index cache.',
  },
  {
    path: SettingsIndexesTableLocation,
    exact: true,
    render: () => 'Table view of the index cache.',
  },
  {
    path: SettingsIndexesChartsLocation,
    exact: true,
    render: () => 'Visual display of the index cache.',
  },
  {
    path: SettingsIndexesManifestLocation,
    exact: true,
    render: () => 'The index manifestation.',
  },
  {
    path: SettingsCachesLocation,
    exact: true,
    render: () => 'View, edit, clean, recover space from the TrueBlocks caches.',
  },
  {
    path: SettingsSkinsLocation,
    exact: true,
    render: () => 'Change the skin or them of the application.',
  },
  {
    path: SettingsDataModelLocation,
    exact: true,
    render: () => 'View and edit the data types for the various screens and tables.',
  },
  {
    path: SupportLocation,
    exact: true,
    render: () => 'Information on contacting TrueBlocks, LLC.',
  },
  {
    path: SupportContactUsLocation,
    exact: true,
    render: () => 'Information on contacting TrueBlocks, LLC.',
  },
  {
    path: SupportDocumentationLocation,
    exact: true,
    render: () => 'Links to various documentation sites.',
  },
  {
    path: SupportHotKeysLocation,
    exact: true,
    render: () => 'A view of all the hot-keys for the program.',
  },
  {
    path: SupportLicensingLocation,
    exact: true,
    render: () => 'Licensing information about the software.',
  },
  {
    path: SupportAboutUsLocation,
    exact: true,
    render: () => 'A short history of TrueBlocks, LLC.',
  },
];
